image: "archlinux"

stages:
  - build
  - test
  - doc

before_script:
  - pacman --noconfirm -Syu
  - pacman --noconfirm -S make cmake clang git python-pip
  - pip install conan

build:
  stage: build
  script:
    - mkdir build && cd build
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan remote add pleiades https://api.bintray.com/conan/ruanformigoni/pleiades
    - conan remote add spdlog https://api.bintray.com/conan/ruanformigoni/spdlog
    - conan remote add fmt https://api.bintray.com/conan/ruanformigoni/fmt
    - conan remote add epfl https://api.bintray.com/conan/ruanformigoni/epfl
    - conan install
      -s compiler=gcc
      -s compiler.version=10
      -s compiler.libcxx=libstdc++11
      --build=missing .. && cd ..
    - cmake -H. -Bbuild
      -D CMAKE_BUILD_TYPE=Debug
      -D CMAKE_CXX_COMPILER=g++
    - cmake --build build
  artifacts:
    paths:
      - ./build/bin/

bfs:
  stage: test
  script:
    - ./build/bin/test_bfs

dfs:
  stage: test
  script:
    - ./build/bin/test_dfs

graph_balance:
  stage: test
  script:
    - ./build/bin/test_balance

a_star:
  stage: test
  script:
    - ./build/bin/test_a_star

matrix_realization:
  stage: test
  script:
    - ./build/bin/test_m_real

barycenter:
  stage: test
  script:
    - ./build/bin/test_barycenter

pages:
  stage: doc
  before_script:
    - ''
  image: "rustlang/rust:nightly"
  script:
    - cargo install mdbook --no-default-features
    - cd ./doc/mdbook/
    - mdbook build
    - mv book ../../public
  artifacts:
    paths:
      - public
  only:
    - master
