image: formigoni/alpine-gcc-10:latest

stages:
  - build
  - test
  - doc

before_script:
  - apk add make cmake clang git py3-pip
  - pip3 install -I conan

build_tests:
  stage: build
  script:
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan remote add pleiades https://api.bintray.com/conan/ruanformigoni/pleiades
    - conan remote add spdlog https://api.bintray.com/conan/ruanformigoni/spdlog
    - conan remote add fmt https://api.bintray.com/conan/ruanformigoni/fmt
    - conan remote add epfl https://api.bintray.com/conan/ruanformigoni/epfl
    - mkdir build && cd build
    - conan install .. --build missing && cd ..
    - cmake -H. -Bbuild
    - cmake --build build
  rules:
    - when: manual
      allow_failure: false
  artifacts:
    paths:
      - ./build/test/
    expire_in: 1 week

.test:
  stage: test
  needs: ["build"]

.artifacts:
  artifacts:
    paths:
      - ./logs/celaeno/
    expire_in: 1 week

# Search
bfs:
  extends: .test
  script:
    - ./build/test/g_search_bfs
  extends: .artifacts

dfs:
  extends: .test
  script:
    - ./build/test/g_search_dfs
  extends: .artifacts

khan:
  extends: .test
  script:
    - ./build/test/g_search_kahn
  extends: .artifacts

# Views
topo:
  extends: .test
  script:
    - ./build/test/g_views_depth
  extends: .artifacts

prox:
  extends: .test
  script:
    - ./build/test/g_views_proximity
  extends: .artifacts

# Operations
## Query
count_crossings:
  extends: .test
  script:
    - ./build/test/g_operations_count_crossings
  extends: .artifacts

incidence_barycenter:
  extends: .test
  script:
    - ./build/test/g_operations_incidence_barycenter
  extends: .artifacts
## Modifiers
balance_paths:
  extends: .test
  script:
    - ./build/test/g_operations_balance_paths
  extends: .artifacts

minimize_crossings:
  extends: .test
  script:
    - ./build/test/g_operations_minimize_crossings
  extends: .artifacts

# Representations
incidence_barycenter:
  extends: .test
  script:
    - ./build/test/g_operations_incidence_barycenter
  extends: .artifacts

# Pages
pages:
  stage: doc
  before_script:
    - ''
  image: "rustlang/rust:nightly"
  script:
    - cargo install mdbook --no-default-features
    - cd ./doc/mdbook/
    - mdbook build
    - mv book ../../public
  artifacts:
    paths:
      - public
