image: "archlinux"

stages:
  - build
  - test

before_script:
  - pacman --noconfirm -Syu
  - pacman --noconfirm -S make cmake clang git python-pip
  - pip install conan

build:
  stage: build
  script:
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan install .
      -s compiler=clang
      -s compiler.version=9
      -s compiler.libcxx=libstdc++11
      -if build
    - conan remote add pleiades https://api.bintray.com/conan/ruanformigoni/pleiades
    - conan remote add epfl https://api.bintray.com/conan/ruanformigoni/epfl
    - cmake -H. -Bbuild
    - cmake --build build
  artifacts:
    paths:
      - ./build/bin/


bfs:
  stage: test
  script:
    - ./build/bin/test_bfs

dfs:
  stage: test
  script:
    - ./build/bin/test_dfs

hvm:
  stage: test
  script:
    - ./build/bin/test_hvm

graph_balance:
  stage: test
  script:
    - ./build/bin/test_graph_balance

a_star:
  stage: test
  script:
    - ./build/bin/test_a_star

cantor_pairing:
  stage: test
  script:
    - ./build/bin/test_cantor_pairing
