[preprocessor]
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[book]
authors = ["Ruan Evangelista Formigoni"]
language = "en"
multilingual = false
src = "doc"
title = "Celaeno - C++ 20 Algorithms"

[output.html]
default-theme = "rust"
no-section-label = false
preferred-dark-theme = "navy"
mathjax-support = true

[output.html.fold]
enable = true
level = 0
